import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/shared/Navbar";
import Sidebar from "./components/shared/Sidebar";
import MobileNavbar from "./components/shared/MobileNavbar";
import MobileSidebar from "./components/shared/MobileSidebar";

const poppins = Poppins({ 
  weight: ["400", "500","600","700","800","900"], 
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="relative bg-[#F9F9F9] h-full overflow-y-auto">
        <Navbar/>
        <Sidebar/>
        <MobileNavbar/>
        <MobileSidebar/>
        {children}
        </div>
        </body>
    </html>
  );
}
